### ISSUE TITLE
TypeError: cb is not a function

### ISSUE THREAD

**Issue by philiprbrenan** [commenthol/xml-vs-js#1]
```
nodejs "test.js"
/home/phil/node_modules/xml-vs-js/src/toJs.js:116
    cb(null, out)
    ^
TypeError: cb is not a function
    at Object.onend (/home/phil/node_modules/xml-vs-js/src/toJs.js:116:5)
    at Parser.onend (/home/phil/node_modules/htmlparser2/lib/Parser.js:324:32)
    at Tokenizer._finish (/home/phil/node_modules/htmlparser2/lib/Tokenizer.js:835:12)
    at Tokenizer.end (/home/phil/node_modules/htmlparser2/lib/Tokenizer.js:826:25)
    at Parser.end (/home/phil/node_modules/htmlparser2/lib/Parser.js:352:18)
    at Object.toJs (/home/phil/node_modules/xml-vs-js/src/toJs.js:137:10)
    at Object.<anonymous> (/home/phil/js/test.js:9:19)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
```

from:

function say(text)
 {process.stderr.write(text+"\n");
 }

const parser = require('xml-vs-js');

const xml = "<a id='1'><b id='b1'/><c id='c1'/><b id='b2'/></a>"

var json = parser.toJs(xml);

say(JSON.stringify(json));

**Comment by commenthol** [comment]
The api is not synchronous. You'll need to pass a callback function as 2nd arg. Please take a look at the example in the Readme.

**Comment by commenthol** [comment]
Closing as this is not an issue related to the library.
